######################################################################
# Automatically generated by qmake (3.1) Thu Feb 27 16:18:43 2020
######################################################################

TEMPLATE = app
TARGET = jag
INCLUDEPATH += /usr/include
QMAKE_CXXFLAGS_ISYSTEM = -I
QT += gui core widgets opengl xml x11extras
LIBS += -lGL -lX11 -lSDL2 -lSDL2_mixer -lpthread -lXrandr

OBJECTS_DIR += src
MOC_DIR += src
RCC_DIR += src
UI_DIR += src

unix: {
	target.path = /usr/games/
	INSTALLS += target
	datas.path = /usr/share/games/jag
	datas.files = data
	INSTALLS += datas
}

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += src/baseitem.h \
           src/bighammertool.h \
           src/bombtool.h \
           src/clocktool.h \
           src/consttools.h \
           src/defines.h \
           src/displaywrapper.h \
           src/gamebackground.h \
           src/gamebonus.h \
           src/gameitem.h \
           src/gamemenu.h \
           src/gameprofile.h \
           src/gamescene.h \
           src/gamesound.h \
           src/gamestat.h \
           src/gamestock.h \
           src/gametools.h \
           src/gamewidget.h \
           src/hammertool.h \
           src/mixertool.h \
           src/randomkilltool.h \
           src/scaler.h \
           src/scene_if.h \
           src/smallhammertool.h \
           src/thundertool.h \
           src/twintool.h \
           src/unblocktool.h \
           src/version.h \
           src/editor/defines.h \
           src/editor/levelpack.h \
           src/editor/levelwidget.h \
           src/editor/mainwindow.h
FORMS += src/menu.ui src/editor/levelpack.ui src/editor/mainwindow.ui
SOURCES += src/baseitem.cpp \
           src/bighammertool.cpp \
           src/bombtool.cpp \
           src/clocktool.cpp \
           src/consttools.cpp \
           src/displaywrapper.cpp \
           src/gamebackground.cpp \
           src/gamebonus.cpp \
           src/gamecontrol.cpp \
           src/gameitem.cpp \
           src/gamemenu.cpp \
           src/gamepaint.cpp \
           src/gameprofile.cpp \
           src/gamescene.cpp \
           src/gamesound.cpp \
           src/gamestat.cpp \
           src/gamestatics.cpp \
           src/gamestock.cpp \
           src/gametools.cpp \
           src/gamewidget.cpp \
           src/gamexml.cpp \
           src/hammertool.cpp \
           src/main.cpp \
           src/menucontrol.cpp \
           src/mixertool.cpp \
           src/randomkilltool.cpp \
           src/scaler.cpp \
           src/smallhammertool.cpp \
           src/thundertool.cpp \
           src/twintool.cpp \
           src/unblocktool.cpp \
           src/editor/levelpack.cpp \
           src/editor/levelwidget.cpp \
           src/editor/main.cpp \
           src/editor/mainwindow.cpp
RESOURCES += src/resources.qrc src/editor/editor.qrc
TRANSLATIONS += data/lang/jag_de.ts \
                data/lang/jag_es.ts \
                data/lang/jag_fr.ts \
                data/lang/jag_it.ts \
                data/lang/jag_nl.ts \
                data/lang/jag_pt.ts \
                data/lang/jag_ru.ts
